import { Canteen, Category, MenuItem, Order } from './types';

export const mockCanteens: Canteen[] = [
  {
    id: '1',
    vendor_id: 'v1',
    name: 'Campus Central Kitchen',
    location: 'Main Building, Ground Floor',
    image_url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400&h=300&fit=crop',
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    vendor_id: 'v2',
    name: 'Green Leaf Cafe',
    location: 'Science Block, Level 2',
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop',
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    vendor_id: 'v3',
    name: 'The Quick Bite',
    location: 'Library Complex',
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400&h=300&fit=crop',
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    vendor_id: 'v4',
    name: 'Spice Junction',
    location: 'Engineering Block',
    image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockCategories: Category[] = [
  { id: 'c1', canteen_id: '1', name: 'Breakfast', image_url: null, created_at: '', updated_at: '' },
  { id: 'c2', canteen_id: '1', name: 'Lunch', image_url: null, created_at: '', updated_at: '' },
  { id: 'c3', canteen_id: '1', name: 'Snacks', image_url: null, created_at: '', updated_at: '' },
  { id: 'c4', canteen_id: '1', name: 'Beverages', image_url: null, created_at: '', updated_at: '' },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: 'm1',
    canteen_id: '1',
    category: 'Breakfast',
    name: 'Classic Pancakes',
    description: 'Fluffy pancakes served with maple syrup and fresh berries',
    price: 89,
    image_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300&h=200&fit=crop',
    is_available: true,
    prep_time: 10,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'm2',
    canteen_id: '1',
    category: 'Breakfast',
    name: 'Veggie Omelette',
    description: 'Three-egg omelette with bell peppers, onions, and cheese',
    price: 75,
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=300&h=200&fit=crop',
    is_available: true,
    prep_time: 8,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'm3',
    canteen_id: '1',
    category: 'Lunch',
    name: 'Grilled Chicken Bowl',
    description: 'Grilled chicken with quinoa, fresh vegetables, and tahini dressing',
    price: 149,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop',
    is_available: true,
    prep_time: 20,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'm4',
    canteen_id: '1',
    category: 'Lunch',
    name: 'Veggie Wrap',
    description: 'Whole wheat wrap with hummus, falafel, and mixed greens',
    price: 99,
    image_url: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=300&h=200&fit=crop',
    is_available: true,
    prep_time: 15,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'm5',
    canteen_id: '1',
    category: 'Snacks',
    name: 'French Fries',
    description: 'Crispy golden fries with special seasoning',
    price: 59,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300&h=200&fit=crop',
    is_available: true,
    prep_time: 10,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'm6',
    canteen_id: '1',
    category: 'Beverages',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice',
    price: 45,
    image_url: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=300&h=200&fit=crop',
    is_available: true,
    prep_time: 5,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'm7',
    canteen_id: '1',
    category: 'Beverages',
    name: 'Iced Coffee',
    description: 'Cold brew coffee served over ice with milk',
    price: 65,
    image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=300&h=200&fit=crop',
    is_available: false,
    prep_time: 5,
    created_at: '',
    updated_at: '',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    user_id: 'u1',
    canteen_id: '1',
    total: 238,
    status: 'pending',
    pickup_code: '4521',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: 'oi1', order_id: 'o1', menu_item_id: 'm1', name: 'Classic Pancakes', price: 89, quantity: 1 },
      { id: 'oi2', order_id: 'o1', menu_item_id: 'm3', name: 'Grilled Chicken Bowl', price: 149, quantity: 1 },
    ],
  },
  {
    id: 'o2',
    user_id: 'u1',
    canteen_id: '1',
    total: 159,
    status: 'ready',
    pickup_code: '7832',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: 'oi3', order_id: 'o2', menu_item_id: 'm4', name: 'Veggie Wrap', price: 99, quantity: 1 },
      { id: 'oi4', order_id: 'o2', menu_item_id: 'm5', name: 'French Fries', price: 59, quantity: 1 },
    ],
  },
];
